### PR TITLE
Add makefile for mingw

### PR DESCRIPTION
**Pull request by mattn**
This is branch of PR from #42

### CODE REVIEW

**Comment by mattn** [comment]
@craigwi If you want single commit, please let me known. I'll squash commits before you will merge.

**Comment by craigwi** [comment]
Thanks @mattn.  There was a comment about the name of the makefile.  I would prefer to have the mingw suffix, but are others ok with that?

**Comment by ZanderBrown** [comment]
I'm not sure I see the point of the prefix

**Comment by tuldok89** [comment]
How about renaming Makefile.mingw to GNUmakefile?

**Comment by ZanderBrown** [comment]
Doesn't make much difference, still have to manually specify the Makefile to `make`

**Comment by tuldok89** [comment]
It does make a difference. GNU Make also reads GNUmakefile by [default](https://www.gnu.org/software/make/manual/make.html#Makefile-Names).

**Comment by ZanderBrown** [comment]
Interesting but
> The first name checked, GNUmakefile, is not recommended for most makefiles. You should use this name if you have a makefile that is specific to GNU make

Is worth noting

**Comment by tuldok89** [comment]
My point exactly. NMAKE doesn't understand this makefile, so I think it's fine to name it `GNUmakefile`.

**Comment by ePirat** [comment]
The makefile does not look GNU make specific to me, so I dont think it should be named `GNUmake`.

**Comment by mattn** [comment]
I renamed Makefile.mingw to GNUmakefile since this makefile use subst as ePirat said.

**Comment by mattn** [comment]
I squashed commits to 1 commit. Please push merge button if you are okay. Thanks.

**Comment by mattn** [comment]
Thanks all!

**Pull request merged**
