### PR TITLE
Enable visual styles.

### PR DESCRIPTION
**Pull request by Azarien**
This enables visual styles of WinXP and later.

### CODE REVIEW

**Comment by daniel-white** [comment]
I think the call to `EnableVisualStyles` is still required.

**Comment by ZanderBrown** [comment]
@daniel-white That's a .NET call i believe

However compiling on MSYS2 the current solution doesn't seem to work

**Comment by daniel-white** [comment]
@ZanderBrown my mistake - its `InitCommonControls`.

From the docs:

> Link to ComCtl32.lib and call InitCommonControls.

**Comment by craigwi** [comment]
Ok, well then what should be the parameters passed to InitCommonControlsEx?

**Comment by Azarien** [comment]
@ZanderBrown: perhaps MSYS compiler does not recognize `pragma comment(linker, ...)` or `/manifestdependency` linker flag. If that compiler has to be supported, we'd need a manifest file the harder way.

**Comment by ZanderBrown** [comment]
@Azarien seems plausable

**Comment by craigwi** [comment]
I prefer the #pragma at the top of the file.  Author credit to @Azarien.

**Comment by corn91791** [comment]
No I did not do this your lifeing 

Christopher Roberson 

On Apr 16, 2018, at 10:48 AM, Craig Wittenberg <notifications@github.com> wrote:

I prefer the #pragma at the top of the file. Author credit to @Azarien.

**Comment by ZanderBrown** [comment]
@corn91791 ?

**Comment by ZanderBrown** [comment]
In theory it's fixed on master

**Comment by NazmusLabs** [comment]
@ZanderBrown yeah, that's what I was asking. If it's fixed in master, that's what I was hoping for. I just couldn't find the PR in the pulse that contains this fix. So I couldn't see when it got in the master branch.

**Pull request closed without merging**
