### PR TITLE
build on mingw compiler

### PR DESCRIPTION
**Pull request by mattn**
include some fixes

### CODE REVIEW

**Comment by mattn** [comment]
Thanks. Which commit you want to separate?

**Comment by craigwi** [comment]
Each commit should be simple and focused on a specific issue.  Just scanning the comments, it looks like most can be separate commits with those about compilation warnings grouped together and those about ^Z grouped together.

Look at it from my point of view.  I really appreciate the help.  The more you can make the changes in bite sized, related pieces the better for you and for me!

**Comment by mattn** [comment]
I separeted some commit. And I noticed usage of CharUpper is not wrong. So removed commits about CharUpper from this PR.

**Comment by mattn** [comment]
If you want to squash commits for the groups, I'll do it.

**Comment by craigwi** [comment]
Thanks; I'll go over the changes again.

**Comment by craigwi** [comment]
Hi @mattn, I took a bunch of the fixes from your PR that were not specific to mingw.

Can you now resubmit your PR with just the remaining changes -- which presumably are just those for mingw?

Thanks.

**Comment by mattn** [comment]
Sorry, GitHub merge tool break encoding of source code. I'll fix in later.

**Comment by mattn** [comment]
Hmm, you've better to use cherry-pick to avoid conflicting.

**Comment by mattn** [comment]
Now this is remaining diffs.

**Comment by craigwi** [comment]
Hi @mattn,

I need you to take a closer look at some things:

1. Why might PARTIALKEY be defined?
2. Why might GUID_DEFINED be defined?
3. the changes to treectl.c are no longer needed since I changed the type of i.
4. the change to wfdrives.c and wfinit.c to include shlobj.h are redundant.
5. the change to wfdirrd.c is wrong since I changed the type of the second parameter to AppendToPath.

Thanks.

**Comment by mattn** [comment]
> 1, Why might PARTIALKEY be defined?

Recent compiler set have HELP_PARTIALKEY in winuser.h

> Why might GUID_DEFINED be defined?

DEFINE_GUID is defined in another implementation in guidef.h on mingw compiler. So need to avoid re-define.

> the change to wfdrives.c and wfinit.c to include shlobj.h are redundant.

No. IsNetDrive is not defined without shlobj.h

**Comment by mattn** [comment]
Now reverted some changes in this PR to match master branch. But the changes you did is changes I did. I say again. You had to use git cherry-pick.

**Comment by craigwi** [comment]
Thanks; all your changes are now merged.

**Comment by mattn** [comment]
Please revert the change https://github.com/Microsoft/winfile/commit/b51bf087dc86acab70b0ab5f439835e10efa6c2f. That is commit I did not you.

**Comment by craigwi** [comment]
Correct.  I cherry-picked your changes and committed some of them.

Let me know _specifically_ what changes I committed that do not meet your needs.

**Comment by mattn** [comment]
Why I don't listed in here https://github.com/Microsoft/winfile/graphs/contributors ? Because you didn't cherry-pick correctly.

**Comment by wataash** [comment]
@craigwi, you should revert b51bf08; otherwise you *stole* code @mattn wrote.

**Comment by Biswa96** [comment]
Is it necessary to add the `.mingw` extention in the makefile? May you remove that extension and rename that file just as `makefile`?

**Comment by Biswa96** [comment]
Is it necessary to add the `.mingw` extension in the makefile? May you remove that extension and rename that file just as `makefile`?

Also it would be nice if you place the project file (.vcxproj), solution file (.sln), makefile outside of the src folder.

**Comment by craigwi** [comment]
I definitely don't want to take credit for others work and clearly made a mistake here.  I will revert this change.  I appreciate the detailed note by @wataash.  

So that I don't make another mistake, how do you want me to remove the commit?  Should I use the checked answer on https://stackoverflow.com/questions/448919/how-can-i-remove-a-commit-on-github?

**Comment by craigwi** [comment]
Commit reverted.

**Comment by mattn** [comment]
@craigwi Thanks for reverting. But still not. Now diff to master branch is below

https://gist.github.com/mattn/047fd972505e9b10ec908c9bcc3d730f

But I worked more.

Below is changes I did not you.
https://github.com/Microsoft/winfile/commit/445ea8ef7018ef02540227591d1aa6ebfa8936ef, https://github.com/Microsoft/winfile/commit/a06f6f19a9eedbbd1fbcd6462737055be8c39eb9

**Comment by mattn** [comment]
This may be a boring thing. Because I always hope to share pleasures that the commits are merged, I care about attribution every time in my repository. Perhaps you are not used to git merging or GitHub. However, this will lower the motivation of the authors of the commit.

**Comment by matarillo** [comment]
@craigwi You should not do `git merge --squash` or `git rebase -i` onto other person's commits; It overwrites the author with your account.
Instead, you can ask the original comitter to do `git rebase -i` oneself and squash the commits.

**Comment by craigwi** [comment]
I feel caught in a bind between wanting high quality commits to a very complex code base and *definitely* wanting to provide attribution to *all* who contribute.  Help me solve that.

**Comment by mattn** [comment]
@craigwi Sorry for confusing. I do not want to say opinions any more because I will be seem I'm talking about childishly. I value the respect for contributors in OSS. For example, I'll keep author name in commit even if I must make squash the commit. If GitHub is gone and I must move my repositories into another VCS, I'll move commit history into the VCS to remain the information of contributions. I feel that this is a difference in respect to contributions. At least if you instructed me, I might make same commit as your commit. If you feel that I don't have the ability to do it, please close this PR.

**Comment by craigwi** [comment]
As I feebly tried to say above, I really, really, really want you all to get the credit for changes.  I've been working on WinFile for 10 years and personally pushed to get this project out so you could all benefit.  I have enough credit to my name here.

In the end, I will:

* make sure the author attribution is correct, no matter how the commit happens
* work more closely with willing authors to shape PR before integration

Given that I already screwed up the commit history, I made one last change so that the most recent commit is authored by Matthew and that he gets the credit on the contributors board.

Again, I want you folks to get the credit and want us to have a great, high quality result.

Sincerely,
Craig.

**Comment by mattn** [comment]
@craigwi Thank you for the faithful and wonderful your work. About twenty years ago, I often used WinFile on Windows 3.1. And it worked very well and charms. I believe that your work was great. Thank you. We are not doubting you. Just simple thing, We hope to share the pleasure of being merge of commits from contributors. So let's make a constructive discuss.

**Comment by mattn** [comment]
@craigwi I'll separete PRs from this PR. If you like single commit, please let us known, I'll squash several commits in the PR before you will merge.

For about separaing PRs, How about this?

* fix syntax of res.rc
* remove compilation warnings
* add Makefile.mingw
* fix build errors related re-define macros.

**Comment by wataash** [comment]
@craigwi 
Thank you for your kind cooperation :)

Please keep remind that git has a concept of "author" and "committer". The committer is just a proxy for commit, while the author is more important.

If the commits in PRs have so good quality that they don't need to be squashed, I recommend merging by "Create a merge commit" or "Rebase and merge" on GitHub UI. But please don't use "Squash and merge". I wrote the details in [here](https://github.com/wataash/git-test-github-merge).

If you need to squash commits, I recommend the following procedure:

```sh
git checkout master
git branch master-backup
git fetch origin pull/42/head:tmp
git reset --hard tmp
git rebase -i master-backup
git branch -d master-backup
git branch -D tmp
```

I wrote more helps in [here](https://github.com/wataash/git-test-squash).
While this procedure, we often get confusing -- *what is the branch status?* and *where am I?*
So I strongly recommend we use a commit-tree visualizing tool like [Sourcetree](https://www.sourcetreeapp.com/) (or, of course, `git log --graph` if you think it's enough).

If you mistakenly rewrite the author, rewrite back again by `git commit --author='Author Name <author@example.com>' [--amend]`.

**Comment by mattn** [comment]
Now this PR is separated to #93 and #94.

**Pull request closed without merging**
