### PR TITLE
Added HotKey string "Ctrl+Shift Enter" to menu-bar

### PR DESCRIPTION
**Pull request by tokomio-sun**
Added HotKey string "Ctrl+Shift Enter" to menu-bar
image

### CODE REVIEW

**Comment by tokomio-sun** [comment]
@microsoft-github-policy-service agree

**Comment by schinagl** [comment]
Except for the change on the German finding, I am fine. 
If I could technically approve I would

**Comment by craigwims** [comment]
@schinagl, does it create more work for you if I merge this now or would you rather I wait for the other changes?

**Comment by schinagl** [comment]
Merge it now. Will push the fixes in an extra PR Right after

**Pull request merged**
