### PR TITLE
Specify product name rather than rely on ntverp default

### PR DESCRIPTION
**Pull request by matthewjustice**
Issue #53 calls out that the Winfile.exe product name is "Windows (R) Win7 DDK driver". This is because res.rc includes ntverp.h, and the version of ntverp.ver that is included with Windows 10 SDK defines the following:

`#define VER_PRODUCTNAME_STR         "Windows (R) Win 7 DDK driver"`

I addressed this by defining the product name as "File Manager", although another product name would be fine if something else is preferred. I also undefined VER_PRODUCTNAME_STR first to avoid resource compiler warning RC4005.

### CODE REVIEW

**Comment by craigwi** [comment]
I would like to combine the AboutDlg changes with this change and do proper build versions.

I am also looking at AppVeyor for build/deploy via Chocolatey.

Anyone have experience with https://github.com/GitTools/GitVersion or recommend something else?

**Comment by matthewjustice** [comment]
I'm working on a change right now that removes the ntverp.h dependency (since it is primarily intended for internal NT builds), and defines the full version, etc in the resource file, and then displays the version info in the AboutDlg. As it stands right, the version number is fully coming from ntverp.h, which we don't want. 

So, I could go ahead and make this change as first step (break the ntverp.h dependency, define version info in the rc file, and display the version in About), and then we could look into ways to automate updating the version number as part of the build process.

**Comment by matthewjustice** [comment]
PR #89, if accepted, will supersede this PR.

**Comment by craigwi** [comment]
I think PR #89 a great change.  I will merge it after I undo the last commit.

**Pull request closed without merging**
