### PR TITLE
make VS2010 happy

### PR DESCRIPTION
**Pull request by ssrlive**
make VS2010 happy

### CODE REVIEW

**Comment by clzls** [comment]
It may be the same idea of #158 . Either we remove all 'for' loop initial declarations, etc. to fit ISO C90 or lower version, or we choose to adopt C99 standard and not to satisfy VS2010.

**Comment by ssrlive** [comment]
I think my commits fit ISO C90.

**Comment by clzls** [comment]
@ssrlive , I mean that we should decide whether to fit C90 or send it to the trash and adopt C99.

**Comment by ssrlive** [comment]
I think it's easy to make the decision. because the code base will not change many and supporting more compilers is a good idea.

**Comment by craigwi** [comment]
This PR is also similar to #59.  The current thinking is that the master branch is compiled using one of two toolsets: VS2017 and mingw.

Right now, it would be easy to make VS2010 work, but the question is whether going forward we support VS2010 indefinitely.  

I agree with a comment @leeter made in #9 and elsewhere: let's stick with modern compilers to get the best code generation, optimization and security features.

Other comments?

**Comment by clzls** [comment]
I second the motion. We should send C90, MinGW 3.x, VS2010s into the trash.
(But I cannot compile it in my VS2017 Community. I bumped into "internal errors" in `BagOValues.h`)

**Comment by ssrlive** [comment]
I have finished the work for Windows XP and VS2010. https://github.com/ssrlive/winfile/tree/winxp 
Bye bye.

**Comment by clzls** [comment]
@ssrlive , WinXP support is in `retro` brunch. Thank you anyway.
Maybe you should read #88 before you start working. See you next time.

**Pull request closed without merging**
