### PR TITLE
Restore XP compatibility

### PR DESCRIPTION
**Pull request by roytam1**
- Downgrade C/C++ syntax to VC2010
- Dynamic loading of Wow64 functions
- Create wrapper of RegGetValue

### CODE REVIEW

**Comment by leeter** [comment]
I don't think this should be merged into master, it significantly holds back the rest of the codebase from using features in C++ that would increase safety and produce a faster better result.

**Comment by NazmusLabs** [comment]
We should combine efforts and use this on a separate retro branch, as others noted.

See issue #3

That way that specific branch can be dedicated to work on as many legacy versions of Windows as possible.

Perhaps we can call it Version 9.x

**Comment by Azarien** [comment]
You don't need to downgrade to VS2010, because you can still use VS2017 to compile XP applications.

**Comment by roytam1** [comment]
@Azarien because I want to dogfood in XP and VC2010 is last version working on XP.

**Comment by NazmusLabs** [comment]
@Azarien Using older versions of VS will not only help @roytam1 help with XP dogfooding but using older libraries makes it easier for it to support even older versions of Windows, such as 2000, and 9x, which is the aim for a retro branch.

**Comment by NazmusLabs** [comment]
Should this PR be merged into the retro branch? Currently the solution in the retro branch is still using VS2015. Or do we want to use versions of visual studios that are older than 2010, such as VS2008 or VS2005.

**Comment by NazmusLabs** [comment]
@roytam1 yes, exactly. The idea is to those changes into the retro branch. That's why the branch was created.

**Comment by craigwi** [comment]
Has anyone tried the Win XP support in VS 2017?  Perhaps that's a way to get an XP build?

**Comment by craigwi** [comment]
Still wondering...

**Comment by roytam1** [comment]
@craigwi this PR may need to be closed in favor of retro branch instead?

**Comment by craigwi** [comment]
OK; thanks for responding.

**Pull request closed without merging**
