### PR TITLE
When cold starting on Win10 with multi monitors, starts basically invisible

### PR DESCRIPTION
**Pull request by tig**
I found on two different Win10 machines with multi-mon, the first time I ran winfile.exe the window was basically just the title bar (zero height client area) and infinitely wide (actually 0x80000000)).

This one line I removed is the cause and I can't see why it would be needed. SystemParametersInfo(SPI_GETWORKAREA) returns the correct RECT.

Did not test on any version of Windows other than Win10...

### CODE REVIEW

**Comment by craigwi** [comment]
Hey Charlie, I thought I tested that, but glad it was a simple fix.

Can you revert the change to .gitignore?  I'll merge your request after that.

**Comment by tig** [comment]
Sorry, my git skillz are lame. I couldn't figure out how to revert the .gitignore change (I actually thought I *had* reverted it before the pull request). I just copied the original over my edited version and added/commited that.

**Comment by x4m3** [comment]
@tig to revert a commit, from the command line, you run `git revert xxx`, where `xxx` is the commit id, you can find it when you run `git log`.

hope it helps in the future :)

**Comment by craigwi** [comment]
Right fix is more complicated.  See my change.  Thanks Charlie!

**Pull request closed without merging**
