### PR TITLE
Making Winfile translatable

### PR DESCRIPTION
**Pull request by peterooch**
Moved all code that can be translatable to winfile.dlg that got renamed to en-US.rc, and now res.rc includes the aforementioned file.
This enables translations that are mentioned at issue #77

Note: for some reason the japanese characters got garbled while making the commit...

### CODE REVIEW

**Comment by peterooch** [comment]
@NazmusLabs Please try with the additional commit that i just added,
Its includes 2 strings from c57f75539c91c461754910850e3d8c7b01e65640

**Comment by craigwi** [comment]
We have a couple different efforts on translation.  I definitely support a translated version, but it isn't clear the right direction, technically.  Can we get some more ideas?

**Comment by mattn** [comment]
https://github.com/Microsoft/winfile/pull/120 has more translations, I guess.

**Comment by peterooch** [comment]
This PR is "ground work" for translations, #120 has some similar changes, but differences in resource file structure/layout and also debate on how to store the files,
i have only done and prefer to edit resource files manually, not in the resource editor of VS,
in there is a different approach for that question.

also  i mentioned there what i think is the best way to handle those resource files.
```
#pragma code_page(65001) //Make rc compiler happy with UTF-8 files
#include "en-US.rc"
#include "zh-CN.rc"
//etc...
```
this method reduces header bloat, only loading one copy for all included files.

**Comment by NazmusLabs** [comment]
Yes I like the idea for the use of res.rc for this as well.

**Comment by MouriNaruto** [comment]
@peterooch 
> i have only done and prefer to edit resource files manually, not in the resource editor of VS,
I edit the resource manually, but the compiler will return error if I use UTF-8 with BOM to save resource files.

Mouri

**Comment by peterooch** [comment]
@MouriNaruto don't use BOM, BOM is evil and screws up UTF-8 files everywhere

**Comment by MouriNaruto** [comment]
I followed your way just now.

Convert resource file to **UTF-8 without BOM** via Notepad++.


But the compiler **was not happy**. And I found It uses code page 936 defaultly (You canknow I use your way if you see my screenshots.).

**Comment by MouriNaruto** [comment]
I also try to use command parameters in the resource compiler options to force it to use UTF-8 code page.
But the compiler returns "RC : fatal error RC1205: invalid code page".

**Comment by MouriNaruto** [comment]
@peterooch 

Also I tried your idea ("only loading one copy for all included files") in UTF-16. Here is the code.
```
#include "res_en-US.rc"
#include "res_zh-CN.rc"
```

But the compiler returns "res_en-US.str(21): error RC2135: file not found: MENUITEM".

**Comment by peterooch** [comment]
@MouriNaruto thank you for trying! I'll look later today at the files and hopefully I'll find a solution.

**Comment by peterooch** [comment]
As PR #120 is more or less the same code wise now, I propose it's merging instead of this one, I think the files need to moved to a sub fo

**Comment by craigwi** [comment]
@peterooch: I agree that we should focus on PR #120 and I agree with your suggestion to move the files to a sub-folder.

**Pull request closed without merging**
