### PR TITLE
Increased quality of icons used in the app - Address #54

### PR DESCRIPTION
**Pull request by NazmusLabs**
Icons outlines have been made darker, returning it back to mostly the way they used to look in Original_plus version and earlier. This PR responds to multiple people showing preference for darker icon outlines, as can be seen on Issue #54.

The screenshots below demonstrates how the look of the icons will be affected with this commit:

Before:

winfile before with gray file outline

First revision:

winfile after with sharp dark file outline

Second revision (current):
winfile icon sprite updates revised

The second revision was made to address feedback from @craigwi.

Note, however, that the icons are not a complete revert to the old look. It's an evolution of the latest bitmaps used in the master branch to increase sharpness and clarity of the icons. Additionally, the directory tree line color has not been reverted to the old look intentionally.

### CODE REVIEW

**Comment by craigwi** [comment]
The changes for folder icons look good to me.  I'm not sure about the document icon changes; many icons I see (e.g., pdf, xls) are not updated (of course) and are of the muted style.  The update made here makes them look out of place.  Thoughts?

**Comment by Anixx** [comment]
Why the tree line color is not changed? I think I would prefer the black one.

**Comment by Biswa96** [comment]
In my opinion, though the icons becomes clear/shiny with these changes, i get some retro feeling with those old icons 😋

**Comment by NazmusLabs** [comment]
@craigwi actually that's a very fair point. The document icon now looks out of place with other native ones. Need to fix that. Thanks!

@Anixx it doesn't look good when you have a black tree line when a lot of folders are open. You get a bunch of parallel lines that looks very distracting. Plus, a grey tree line is the standard in modern operating systems.

**Comment by NazmusLabs** [comment]
@craigwi I've updated the bitmap to make the file icons more consistant. Here's how it looks now.
winfile icon sprite updates revised

@Anixx So, to give you a visual understanding why I chose not to restore the tree line colors to the black used in Original_plus and earlier, I am attatching this screenshot to demonstrate that the current, subtler, gray color is better and less distracting.

winfile original_plus black tree line

**Comment by craigwi** [comment]
Looks good to me.

**Pull request merged**
