### PR TITLE
Add Turkish localisation

### PR DESCRIPTION
**Pull request by bitigchi**
See title. Includes original translations, with improvements and missing ones by me.

### CODE REVIEW

**Comment by craigwi** [comment]
Hi @bitigchi, all looks good except that you need to make an addition to wfloc.c around line 24.

**Comment by bitigchi** [comment]
@craigwi, thanks for checking. It should be okay now.

**Comment by craigwi** [comment]
For the record, I ran Microsoft's policheck tool on the files and the tool found no issues.

**Comment by bitigchi** [comment]
Thank you. I'll check it further with the master builds later on, and fix if anything's not right.

**Pull request merged**
