### PR TITLE
Add Portuguese translation

### PR DESCRIPTION
**Pull request by jcfb-opensource**
The majority of text was copied from the windows 98SE portuguese winfile translation with some small changes.
I've also fixed spacing issues in the dialogs

### CODE REVIEW

**Comment by jcfb-opensource** [comment]
@microsoft-github-policy-service agree

**Comment by schinagl** [comment]
There must be something missing in your PR:
If I chose Portugese
image
and restart Winfile it is still in English

**Comment by jcfb-opensource** [comment]
@schinagl You're right, I forgot to add the include line to the res.rc file.
I also added the translation files to the vc project.
Sem título

**Comment by schinagl** [comment]
Works now on my end.

Please move the files in the .vcxproj to the lang/ folder. Thx

**Comment by jcfb-opensource** [comment]
Did you mean moving the .rc file include line from where it was to the list below? Because the files are already in the lang/ folder.
before

after

**Comment by schinagl** [comment]
Looks like I had a old version of your branch.
You are right the files are in the correct folder

For me this looks fine.

**Review by schinagl — APPROVED** [review]

**Comment by schinagl** [comment]
@craigwi, @malxau: Tried, works as far as I can see. ==> I guess we can merge this to the main trunk

**Pull request merged**
